// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
export const metadata = {
  title: 'Recipe App',
  description: 'A simple recipe app with Next.js and Tailwind CSS',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans bg-gray-50 text-gray-900">
        <nav className="bg-blue-500 text-white py-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">Recipe App</h1>
            {/* Responsive Navigation */}
            <div className="space-x-4 hidden md:flex">
              <a href="/" className="hover:underline">Home</a>
              <a href="/all-meals" className="hover:underline">All Meals</a>
              <a href="/favorites" className="hover:underline">Favorites</a>
            </div>
          
            <div className="md:hidden">
              <button className="text-white">☰</button> 
            </div>
          </div>
        </nav>
        <main className="container mx-auto py-8">{children}</main>
      </body>
    </html>
  );
}
